### ISSUE TITLE
Can I modify data?

### ISSUE THREAD

**Issue by lassediercks** [u12206050/gridsome-source-firestore#2]
At first I like to provide a little context.

I'm a Ui-Engineer, I'm superb at HTML,CSS and I know how to build basic things in JS.
Gridsome & Vue enabled me to go a little deeper without knowing a lot about it.
Now I'm looking at firestore and stumbled upon your package.

Thanks for your work, I was able to fetch data from my firestore and I love it!!!

**Is it also possible to modify/update data with the firestore reference?**

I couldn't find documentation in your package how to update firestore data. 
Also maybe it's a lack of my understanding how the gridsome source works but my question would be, does this package also enable me to update my firestore data?

Again, thanks for publishing your work! It makes my live easier. 

Cheers

**Comment by u12206050** [comment]
Hey, if you are looking for an admin dashboard to edit things then you could try and use: [Firebase Admin](https://github.com/u12206050/gridsome-firebase-admin)
Otherwise you can use the normal firestore api to update things, make sure you have proper rules in place to only allow the desired actions, otherwise someone can very easily bypass your site and just start inserting/updating your content, so don't trust the frontend.

**Comment by lassediercks** [comment]
thanks so much!!!
